FROM python:3.10-slim
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        libssl-dev \
        libffi-dev \
        python3-dev \
        bash \
    && rm -rf /var/lib/apt/lists/*
COPY ./requirements.txt .
RUN pip install --upgrade pip && \
    pip install -r requirements.txt
RUN rm ./requirements.txt
