FROM python:3.9-alpine
RUN apk update && \
    apk add --no-cache \
        build-base \
        libressl-dev \
        libffi-dev \
        python3-dev \
        bash
COPY ./requirements.txt .
RUN pip install --upgrade pip && \
    pip install -r requirements.txt
RUN rm ./requirements.txt
